export { ReactComponent as IcoBack} from './back.svg'
export { ReactComponent as IcoMenu} from './menu.svg'
export { ReactComponent as IcoSearch} from './search.svg'
export { ReactComponent as IcoBell} from './bell.svg'
export { ReactComponent as IcoAdd} from './add.svg'
export { ReactComponent as IcoUser} from './user.svg'
export { ReactComponent as IcoClose} from './close.svg'
export { ReactComponent as IcoPointer} from './pointer.svg'